#!/usr/bin/bash

cd /home/anon/github/iicm-site
git pull origin main
/home/anon/miniconda3/bin/python3 updateMenu.py
git add src/pages/menu.astro
git commit -m "automated menu-update $(timedatectl | grep -i 'local time' | awk -F : '{$1=""; print $0}')"
git push origin main
